version: '3'

services:
  frontend:
    image: rayenkharbeche/hotelwallet:latest
    ports:
      - "4200:4200"
    environment:
      - DATABASE_URL=mongodb+srv://sabreenchouaib:sabsab@cluster0.zbhmylj.mongodb.net/hotel?retryWrites=true&w=majority
      - SENDGRID_API_KEY=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
      - SENDGRID_EMAIL_SENDER=sabreen.chouaib@gmail.com
      - JWT_SECRET=e5412e5c4be14b335f160580084ec11f6458a2ba5845a7085a15830a3cd0cd579d35c9bffaa72448d40dbb6a15d001a0a1026d3108fed0089aa08118dc4de27c
      - URL=http://localhost:4200

 